version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: votacao_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: votacao
    ports:
      - "3306:3306"
    volumes:
      - votacao_data:/var/lib/mysql
      - ./backend/src/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  votacao_data:
